formatter: "md tbl" # this is required

version: ">= 0.14"

sections:
  hide: []
  show: [all]

content: |-
  ## Usage
  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  ## Consumption Budget
  You can create a consumption budget for the resource group and setup notifications based on various thersholds.

  ```hcl
    consumption_budgets = {
      default = {
        amount = 100
        time_period = {
          start_date = "2022-07-01T00:00:00Z"
        }
        notifications = {
          forecastedGreaterThan100 = {
            contact_emails = ["notify@example.com"]
            operator       = "GreaterThan"
            threshold      = 100
            threshold_type = "Forecasted"
          }
        }
      }
    }
  ```

  > This module supports only e-mail addresses for notification.

  ## Examples

  - [Basic Resource Group](https://github.com/getindata/terraform-azurerm-resource-group/tree/master/examples/basic)
  - [Resource Group with Consumption Budget](https://github.com/getindata/terraform-azurerm-resource-group/tree/master/examples/full-example)

  {{ .Header }}

  {{ .Footer }}

  {{ .Inputs }}

  {{ .Modules }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
